### ISSUE TITLE
Binary build/release?

### ISSUE THREAD

**Issue by gingerbeardman** [myelin/rpcemu-macos#1]
Is there a downloadable binary of this fork of RPCEmu?

Would love to try it.

Thanks!

**Comment by myelin** [comment]
That's a good idea :)  I'll see about getting one up!

**Comment by myelin** [comment]
Here we go -- give this a try: https://github.com/myelin/rpcemu-macos/releases/tag/0.9.1-pp1

Please let me know if it works, or if not, exactly what error you get, so I can fix it.  I suspect I'll need to vendor Qt in there.

**Comment by gingerbeardman** [comment]
Yay! That works a treat — thank you! 

I didn't even need to update Qt as I'm fairly up-to-date with `brew`. On first launch I just had to select my old RPCEmu directory at `~/Library/Application Support/RPCEmu/` — could your build maybe check for that and automatically use it if it exists?

I can now even screen grab the window [which I was unable to do in the old version](https://user-images.githubusercontent.com/49612/57194343-98472b80-6f3d-11e9-9225-4d25438d1eb0.png). ~~It seems slower than the older version, I'll use it more before I say with any certainty.~~

~~I also do not understand how I can ADJUST click? So I cannot progress from this screen in the game I'm playing. I need to adjust click the blue card. In the old version I had to switch on the "two button mode" option, which then made alt-click on macOS act as adjust-click on RISC OS.~~ Managed to figure out some settings that allow me to adjust-click.
![Screen shot 2019-05-05 at 13 39 34](https://user-images.githubusercontent.com/49612/57194145-3be30c80-6f3b-11e9-92e7-58a04bb5c44b.png)

Is Network still not available on macOS in this newer build?

In your preferences, whilst the emulator is running, i need to double click radio buttons and confirm buttons (like the one confirming reset after making changes) to get them to take effect?

Once you're happy with a release, you might want to submit that to the [RPCEmu website](http://www.marutan.net/rpcemu/index.php) to replace the ancient macOS 0.8.x download I was using.

I also spotted on the ROOL forum (I've not registered so can only read) that you have a build of Arculator. Which do you recommend? I had the old RPCEmu running so I'm happy enough, my RISC OS 5 setup was maintained when changing to use your updated binary.

Thanks again!
