### ISSUE TITLE
MBP control-fn-right doesn't exit full-screen mode

### ISSUE THREAD

**Issue by myelin** [myelin/rpcemu-macos#12]
**Describe the bug**
The dialog that pops up when you enter full-screen mode says to hit Ctrl-END to exit.  END is fn-right on a MacBook Pro keyboard, so the expectation here is that control-fn-right will exit full-screen mode, but in reality it does nothing.

**To Reproduce**
1. Settings | Full-screen Mode
2. Click through dialog
3. When in full-screen mode, hit control-fn-right
4. Nothing happens

**System information (please complete the following information):**
 - machine: MBP 15" mid-2015
 - rpcemu-macos release: 0.9.1-pp2
 - macOS version: Mojave
 - Emulated processor: ARMSA
 - RISC OS version: 5.24

**Comment by Septercius** [comment]
Having looked at the code, there is at least one issue with the CTRL+END detection code, as it looks at the key event modifier state to determine whether CTRL is held down. This information isn't populated on the Mac, and you have to use a different way of detecting modifier key presses and releases (see the "keyboard_macosx.c" file).

This will need a change to expose the modifier state outside the mentioned file, which can then be picked up by the CTRL+END .  This should (hopefully) be fairly straightforward.

**Comment by Septercius** [comment]
I've fixed this, so it can be included in the next patch which I'll submit to the RPC mailing list as normal.

**Comment by myelin** [comment]
Confirmed that this is fixed in https://github.com/myelin/rpcemu-macos/releases/tag/0.9.1-pp3.  Thanks!
