### ISSUE TITLE
256MB RAM configuration not working

### ISSUE THREAD

**Issue by RichardHallas** [myelin/rpcemu-macos#14]
I'd really like to run RPCEmu with 256MB of RAM available to the emulator. However, although I haven't seen anything about this in any related documentation I've read, it simply won't boot with this configuration enabled.

It starts up with "RISC OS 264MB" [or "256MB" if VRAM is disabled] and reports the processor type, and then you see the "RPCEmu Host Filing System" line… and then it hangs.

So I'm stuck with 128MB. Being able to run with 256MB is actually quite important to me. Can it be done?

**Comment by myelin** [comment]
This sounds possibly like a general RPCEmu bug; flagging as such for now.

**Comment by Septercius** [comment]
I tried using 256MB with both RISC OS 3.71 and the latest stable 5.24 from the RISC OS Open site and it boots to the desktop without issue.  This is using a very basic setup without a !Boot application or anything else.

**Comment by RichardHallas** [comment]
OK, I've done another quick test, and the result surprised me, though it's little different in the end.

NB the OS I've got installed is 5.24 – though I've previously used other versions of RISC OS 5 with RPCEmu, and no version has *ever* worked wth 256MB of RAM for me.

To eliminate the question of the boot sequence being the problem, I did a quick "*configure noboot" on the desktop, to prevent future booting, and relaunched the emulator. As expected, I got the Supervisor prompt and was then able to type *desktop to go straight to the vanilla desktop.

So, next I reconfigured RPCEmu with 256MB of RAM. Surprise! On rebooting I got as far as seeing the Supervisor prompt! HOWEVER… then I noticed that there was no flashing underscore cursor. I tried typing 'desktop', and… no response. Emulator was locked up. I could see the * prompt, but there was no cursor and obviously no response when I typed. And that's with the emulator having done NOTHING with anything on disk. It should just start up, give me the prompt and let me type something. But I get the prompt immediately followed by a lock-up.

This is on Recompiler. With Interpreter, I see nothing different from before, i.e. it still locks up after reporting "RPCEmu Host Filing System"; I don't even get as far as the * prompt with Interpreter.

Anyway, I think I've eliminated the !Boot sequence from the equation, and since I'm apparently using the same OS that works for Septercius (i.e. 5.24) it's all rather mysterious.

Final test: I tried removing my cmos.ram file, too, with the emulator configured to 'noboot' and with 256MB of RAM. This didn't help either. This time there was no reference to "RPCEmu Host Filing System" and instead I got a "Supervisor" prompt, but no * and still a locked-up emulator. So the contents of the CMOS RAM don't appear to be the source of the problem either.

Given that I've eliminated the CMOS RAM contents and the hard drive contents as sources of the lock-up, I'm having trouble understanding how this 256MB configuration will work for someone else but not for me.

In case it matters, this particular iMac is still on Sierra. I'll probably upgrade it to Mojave soon, but for the moment it's two major OS versions behind the times. However, my laptop's on Mojave. I haven't tried that with RPCEmu 0.9.1 yet, but I could do. (At the moment it has 0.9.0, which I compiled myself.) Based on prior experience, I'd be surprised if it doesn't behave in exactly the same way.

**Comment by gingerbeardman** [comment]
I just tried and 256MB works for me.

- Setup using [this guide](https://www.riscosopen.org/wiki/documentation/show/RPCEmu%20and%20RISC%20OS%205%20on%20Mac%20OS%20X)
- RPCEmu 0.9.1 recompiler
- RISC OS 5.24 open 
- macOS 10.13.6 High Sierra

![Screen shot 2019-05-11 at 21 26 03](https://user-images.githubusercontent.com/49612/57574571-664d3200-7433-11e9-92f4-5e26f16b0a15.png)

![Screen shot 2019-05-11 at 21 24 14](https://user-images.githubusercontent.com/49612/57574568-559cbc00-7433-11e9-9dc0-d855e8e20b5a.png)

**Comment by RichardHallas** [comment]
Hmph! I'm mystified. Further investigation required…

**Comment by RichardHallas** [comment]
OK, I've downloaded a new ROM from RISC OS Open Ltd and the problem has gone away. I've tested both a fresh copy of 5.24 and the current 5.27 beta, and with both of them, RPCEmu now works fine with 256MB of RAM.

So, apologies for the false report. It seems the problem was caused by some temporary ROM-related issue that's now gone away. All's well. I'll close this topic.
