### ISSUE TITLE
Missed mouse clicks (+workaround)

### ISSUE THREAD

**Issue by gingerbeardman** [myelin/rpcemu-macos#6]
In preferences, whilst the emulator is running, I need to double click radio buttons and confirm buttons (like the one confirming reset after making changes) to get them to take effect?

Also restart alert needs this.

**Comment by gingerbeardman** [comment]
clicks in the emulator also seem less than responsive

**Comment by Septercius** [comment]
Do you have the "Reduce CPU usage" menu item turned on?

**Comment by gingerbeardman** [comment]
No I do not

**Comment by gingerbeardman** [comment]
As noted issue #3 it seems yesterday I did in fact have "Reduce CPU Usage" turned on. Sorry.

So today I have confirmed it is _off_ and recorded some videos:

**"missed" clicks in the UI**
- 0:07 (radio button gets half focused but does not become selected)
- many other similar instances
- 0:23 (reset alert button changes focus/colour but is not selected)
https://imgur.com/a/XgfJUbn

**missed clicks in RISC OS**
- 0:04 (app should launch)
https://imgur.com/a/vzEXlRH

**Workaround**
If I keep each mouse click pressed for longer than I usually do, then no clicks are missed.
So instead of a fraction of a second click (button down, then up) I hold the mouse button down for something like half a second.

**Why would single clicks not be recognised?** 
Could RPCEmu/Qt be ignoring mouse clicks quicker than a specified period of time?

**Comment by gingerbeardman** [comment]
Could be useful https://www.qtcentre.org/threads/69457-In-Qt-5-10-1-why-do-I-need-to-click-twice-on-a-QPushButton-to-get-a-release-event?highlight=qt+click+timing

**Comment by gingerbeardman** [comment]
Still present in 0.9.1-pp3

**Comment by gingerbeardman** [comment]
Solved in build 0.9.2 mac-patch-v2

https://homepages.plus.net/pittdj/rpcemu/
